### ISSUE TITLE
WvW Desert borderland tiles missing sand border at zoom level 3

### ISSUE THREAD

**Issue by vennekilde** [arenanet/api-cdi#541] opened 2017-06-06 11:42 UTC
The desert borderlands at zoom level 3, still (if my memory serves me right) use the old tiles from before the sand was added to surround the map to make it fit it

Example
https://tiles2.guildwars2.com/2/1/3/4/5.jpg

Zoom in bottom right corner with sand
https://tiles1.guildwars2.com/2/1/4/9/11.jpg

Full size comparison
http://i.imgur.com/2iQIp2j.png
http://i.imgur.com/G71ueZm.png

**Comment by vennekilde** [comment] 2017-06-06 11:44
In case someone is using leaflet and is extremely bothered by this, they can set minNativeZoom: 4 at the tile layer. 
This will however force it to load more tiles in higher resolution than necessary

**Comment by lye** [comment] 2017-06-06 15:59
I'm going to regenerate the map tiles today; will see if that fixes it.

**Comment by lye** [comment] 2017-06-06 22:39
Regenerated the tiles and the issue is still present.

_hmm_

**Comment by lye** [comment] 2017-06-06 23:00
So I checked in-game, and that's how it looks in-game.

The tiles are generated by uhh, effectively taking screenshots of the in-game world map (don't worry, it's automated somewhat). The API is faithfully reproducing the in-game bug, so I'm going to close this one out. I'll poke someone that they should ... maybe look at that? I don't really know how the area around the map gets generated >_>

**Closed by lye** 2017-06-06 23:00 UTC
Labels: Bug, ready
