### ISSUE TITLE
"New Key" button disabled

### ISSUE THREAD

**Issue by Teranas** [arenanet/api-cdi#131] opened 2015-12-07 16:28 UTC
Hi,

I don't know if it is intended or not but I noticed that the "New Key" button on the application page of the account management site is disabled.

However, it's still possible to add a new key by clicking the link in the description.

![download](https://cloud.githubusercontent.com/assets/4856033/11632523/de2855b8-9d07-11e5-9f23-abee6ddd0aa8.png)

Greetings,
Teranas

**Comment by Aralicia** [comment] 2015-12-07 16:43
Just confirmed the issue : happens on Chrome and Firefox.
The button is given the class "pure-button-disabled" which not only change it appearance, but also seems to disable its functionality.

**Comment by lye** [comment] 2015-12-07 16:51
Heh, was just about to open the same bug. Looks like we updated some templates, but the deploy didn't include the backend part with the max keys/user, so the template makes it look like you can't create more keys. I'll have this fixed in a bit.

**Comment by lye** [comment] 2015-12-07 17:13
Just deployed the fix. Thanks for the bug report :>

**Closed by lye** 2015-12-07 17:13 UTC
Labels: Bug, needs deploy
