### ISSUE TITLE
pvp_rank_points in /v2/pvp/stats wrong

### ISSUE THREAD

**Issue by darthmaim** [arenanet/api-cdi#366] opened 2016-09-26 08:13 UTC
The `pvp_rank_points` in /v2/pvp/stats are wrong. This is the a f2p account I never played pvp with (ingame shows 0/500), but it still returns 500 in the api: https://api.guildwars2.com/v2/pvp/stats?access_token=CB0EA922-28D1-F745-9253-2A4D0AD38EAAC2928255-2CD1-457F-A328-38373ED49C35.

It seems that the points in higher ranks diverge even more. My main account has 318/1500 (rank 8) ingame, but 2318/1500 according to the api and this list of the rank requirements on the wiki: https://wiki.guildwars2.com/wiki/PvP_Rank#Rank_requirements.

gitter ref starting at https://gitter.im/arenanet/api-cdi?at=57e6ecc657bec07c30f09eed

**Comment by lye** [comment] 2016-09-27 00:46
The rank point at high levels is because the wiki vales are wrong. I'll update this thread tomorrow with the correct values (and maybe the wiki? Not sure if I have access).

The "new account has 500 rank points" is not a bug. Bear with me on this one:

 * New accounts start at rank 0.
 * From rank 0 to rank 1 is 500 points.
 * There is no rank 0, so the account is bumped up to rank 1.
 * The account has less exp than the rank requires, so it's run through the migration process from when we changed the rank points (2013? 2014?). The code says "you are level 1, so here's 500 points to make that true".

The UI displays the amount needed to get to level 2 (1000 total rank points) from level 1(500 total rank points). Since the account has 500, it has 0/500 points needed to reach level 2.

:ship it:

**Comment by lye** [comment] 2016-09-27 16:54
Here are how the ranks are currently:

```
[
  {
    "id": 1,
    "finisher_id": 1,
    "name": "Rabbit",
    "icon": "http://localhost",
    "min_rank": 1,
    "max_rank": 9,
    "levels": [
      {
        "min_rank": 1,
        "max_rank": 5,
        "points": 500
      },
      {
        "min_rank": 6,
        "max_rank": 9,
        "points": 1500
      }
    ]
  },
  {
    "id": 2,
    "finisher_id": 2,
    "name": "Deer",
    "icon": "http://localhost",
    "min_rank": 10,
    "max_rank": 19,
    "levels": [
      {
        "min_rank": 10,
        "max_rank": 19,
        "points": 4000
      }
    ]
  },
  {
    "id": 3,
    "finisher_id": 3,
    "name": "Dolyak",
    "icon": "http://localhost",
    "min_rank": 20,
    "max_rank": 29,
    "levels": [
      {
        "min_rank": 20,
        "max_rank": 29,
        "points": 7500
      }
    ]
  },
  {
    "id": 4,
    "finisher_id": 4,
    "name": "Wolf",
    "icon": "http://localhost",
    "min_rank": 30,
    "max_rank": 39,
    "levels": [
      {
        "min_rank": 30,
        "max_rank": 39,
        "points": 15000
      }
    ]
  },
  {
    "id": 5,
    "finisher_id": 5,
    "name": "Bear",
    "icon": "http://localhost",
    "min_rank": 50,
    "max_rank": 59,
    "levels": [
      {
        "min_rank": 50,
        "max_rank": 59,
        "points": 20000
      }
    ]
  },
  {
    "id": 6,
    "finisher_id": 6,
    "name": "Tiger",
    "icon": "http://localhost",
    "min_rank": 40,
    "max_rank": 49,
    "levels": [
      {
        "min_rank": 40,
        "max_rank": 49,
        "points": 20000
      }
    ]
  },
  {
    "id": 7,
    "finisher_id": 7,
    "name": "Shark",
    "icon": "http://localhost",
    "min_rank": 60,
    "max_rank": 69,
    "levels": [
      {
        "min_rank": 60,
        "max_rank": 69,
        "points": 20000
      }
    ]
  },
  {
    "id": 8,
    "finisher_id": 8,
    "name": "Phoenix",
    "icon": "http://localhost",
    "min_rank": 70,
    "max_rank": 79,
    "levels": [
      {
        "min_rank": 70,
        "max_rank": 79,
        "points": 20000
      }
    ]
  },
  {
    "id": 9,
    "finisher_id": 9,
    "name": "Dragon",
    "icon": "http://localhost",
    "min_rank": 80,
    "max_rank": 81,
    "levels": [
      {
        "min_rank": 80,
        "max_rank": 81,
        "points": 20000
      }
    ]
  }
]
```

**Comment by milneti** [comment] 2016-11-06 21:42
Is this not the same as what the wiki says for the higher levels? I don't see the 2k point difference here... Maybe I just can't count? :)

**Comment by queicherius** [comment] 2016-11-07 14:50
@milneti This table by @Archomeda shows it better: https://gist.github.com/queicherius/a69111817b073027c86f61c9d58cacc9. The "Achievement points" row is the correct value, bold values are where the wiki is wrong.

**Comment by Archomeda** [comment] 2016-11-07 19:25
Well, you improved it, mine was just a quick table 😄

**Comment by lye** [comment] 2016-11-30 16:25
Turned on the `/v2/pvp/ranks` endpoint yesterday to make it possible to data-drive the rank values, so I'm going to close this one out.

**Closed by lye** 2016-11-30 16:25 UTC
Labels: Bug, needs deploy
