### ISSUE TITLE
Add API endpoint to retrieve World Boss Daily Completion

### ISSUE THREAD

**Issue by CodyDunlap** [arenanet/api-cdi#555] opened 2017-08-11 22:40 UTC
I would like to petition ArenaNet to add an API endpoint to allow us to retrieve info about what world bosses the user has already completed for the day based on the API key, much like the /v2/account/dungeons endpoint.

**Comment by Archomeda** [comment] 2017-12-22 16:04
Dupe of #487

**Closed** 2017-12-22 18:45 UTC
Labels: Feature, ready
