### ISSUE TITLE
bug:  guild/:id/log and missing pumpkin creator

### ISSUE THREAD

**Issue by FreezyExp** [arenanet/api-cdi#384] opened 2016-10-22 22:12 UTC
The pumpkins show up in the log, but it lacks the information on who put in the decoration parts.
I am not sure at the moment whether this is with candy-corn specifically, or with decorations in general.

The data is shown in game, so hopefully it will be resolved in a way that the log will show this information in the future.

**Comment by lye** [comment] 2016-11-30 16:24
Sorry for the belated reply, could you give me a guild ID that has the offending events in the log?

**Comment by FreezyExp** [comment] 2016-12-01 11:07
The log entries are gone now entirely.
I guess upgrade log is limited to 50 entries.

The decoration log (type upgrade) does not seem to log the activity user at all 90% of the time.
Even with the same decoration, the behavior seems to be very irregular.

**Comment by loriamor** [comment] 2016-12-17 00:02
Using guild id C81DECB9-CA12-E411-9621-AC162DAE8ACD we have a bunch of anonymous snow piles being added into the log. Upgrade id is 661 also chak gerent eyes with id 676

**Comment by lye** [comment] 2016-12-19 21:13
Haven't managed to repro this 100% locally, but I can see what the issue is with your guild data. I think I'm parsing different events than the client -- and the events I'm looking at have zero'd player references. Going to adjust the API implementation to look at the *correct* events and that should fix the issue, I think.

**Comment by lye** [comment] 2017-01-09 22:46
This should be fixed, with the caveat that #425 will still be an issue for awhile.

**Closed by lye** 2017-01-09 22:46 UTC
Labels: Bug, needs deploy
