### ISSUE TITLE
/v2/guild/:id/treasury broken

### ISSUE THREAD

**Issue by hackedd** [arenanet/api-cdi#212] opened 2016-02-03 21:19 UTC
It returns a HTTP 400 response:

    {
        "text": "endpoint broken"
    }

**Comment by lye** [comment] 2016-02-04 00:51
What's the guild GUID?

**Comment by hackedd** [comment] 2016-02-04 09:34
`7F1FC74C-8BDB-E411-A278-AC162DC0070D`

Is it possible that this error is returned because the treasury is empty?

**Comment by lye** [comment] 2016-02-12 21:10
The fix for this is deployed -- it takes me an hour or so to fumble through and manually forge an API key on live, but my tests indicate the fix works on all non-live environments.

@hackedd if the issue isn't corrected, re-open the issue and I'll figure out why it's still broken :<

**Closed by lye** 2016-02-12 21:10 UTC
Labels: Bug, needs deploy

**Comment by hackedd** [comment] 2016-02-12 21:21
Seems to work now, thanks :+1:
