### ISSUE TITLE
Missing skins under /v2/skins

### ISSUE THREAD

**Issue by codemasher** [arenanet/api-cdi#78] opened 2015-08-08 12:24 UTC
https://api.guildwars2.com/v2/skins/2984 yields an ```ErrBadParam``` while this id is listed under ```/v2/skins```.
Also, the HTTP error should rather be a ```204/No Content``` than a ```400/Bad Request``` - the latter sounds so passive aggressive... :P

**Comment by tivac** [comment] 2015-08-09 21:52
That's a generic error message, and a `20x` response code would be inappropriate for bad parameters from a client.

That said, this appears to be a bug & I'll try to poke at it tomorrow.

**Comment by codemasher** [comment] 2015-08-13 16:16
A ```HTTP/20x``` response as generic is for sure inappropirate. However, the errors should at least indicate if it was a user error or a backend failure. Altough my above example might be the result of a bug, the ```HTTP/400``` was clearly wrong and caused me to review and test my code a couple times before i opened this issue because it implied that the error was on my side.

**Comment by StevenLiekens** [comment] 2015-09-28 16:41
It's not just 2984. Here's the full list.

https://api.guildwars2.com/v2/skins?ids=1042,1043,1047,1193,2329,2385,2388,2393,2394,2395,2984,3046,6074

**Comment by darthmaim** [comment] 2015-09-28 16:59
Really, who cares that much about the response codes. Its an error. The bug is with serializing the skin for the api (or listing it when it shouldn't be listed). This should be fixed. Changing the response code doesn't help anyone. Half of the comments on issues here in this repo or just about response codes, and not about the bug itself. 
Changing the response code makes sense when its something that is expected to happen (requires authentication, rate limiting, partial content, ...), this is a bug with the implementation underneath, any error code tells the consumer its not what they requested. If its 400 for requesting a broken entry or a 500 because the api server had some error when processing doesn't matter in this case, once its fixed it is fixed, until then it throws an exception in the client.

<sup>/rant over</sup>

**Comment by StevenLiekens** [comment] 2015-09-28 17:12
Lol jeez

**Comment by lye** [comment] 2015-09-28 18:40
> It's not just 2984. Here's the full list.

I just removed all of those skin IDs from the whitelist -- `ErrBadParam` usually means the server which reads the `.dat` file is refusing to serve the content. There's one flag which, looking at it now, might be the cause -- if `ShowInWardrobe` isn't set the skin is always suppressed. I'll keep an eye on it -- those skins will come back through the whitelist if that hypothesis is correct and I'll be able to fix the issue more correctly.

I should drink some coffee.

**Comment by darthmaim** [comment] 2015-09-29 18:45
[5898](https://api.guildwars2.com/v2/skins/5898) is also returning `ErrBadParam`.

**Comment by darthmaim** [comment] 2015-10-06 21:12
> I'll keep an eye on it -- those skins will come back through the whitelist if that hypothesis is correct and I'll be able to fix the issue more correctly.

[2329](https://api.guildwars2.com/v2/skins/2329) is back.

**Comment by Freema** [comment] 2015-10-11 00:12
Skin id [5898](https://api.guildwars2.com/v2/skins/5898) still return status 400 :(

**Comment by lye** [comment] 2015-10-14 17:15
Just re-blacklisted 2329 and 5898. Haven't had time to look into what exactly wrong with these, but given that it came back I really think it's some bad content somewhere.

**Comment by lye** [comment] 2015-12-07 16:03
I'm gonna close this one out for now. smh.

**Closed by lye** 2015-12-07 16:03 UTC
